[project]
name = "opencv_st"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "opencv-python>=4.11.0.86",
    "streamlit>=1.43.2",
    "watchdog>=6.0.0",
]
